lane :test1 do
   sh("rm -rf ../bluepill")
   sh("rm -rf ../bluepill_output")
  scan(
    scheme: 'BullsEye',
    build_for_testing: true,
    derived_data_path: './bluepill',
    buildlog_path: './bluepill/logs/'
  )
  bluepillar(
    app: 'bluepill/Build/Products/Debug-iphonesimulator/BullsEye.app',
    runner_app_path: 'bluepill/Build/Products/Debug-iphonesimulator/BullsEyeUITests-Runner.app',
    scheme_path: 'BullsEye.xcodeproj/xcuserdata/rubhatt.xcuserdatad/xcschemes/BullsEye.xcscheme',
    output_dir: 'bluepill_output/',
    num_sims: '1',
    runtime: '"iOS 10.3”’,
    device: 'iPhone 5s’
  )
end